name: plant_disease_detector
description: A super-intelligent AI Plant Disease Detector app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # AI & Camera
  tflite_flutter: ^0.12.1 # Updated to fix build error
  camera: ^0.10.5
  image_picker: ^1.0.4
  # UI
  percent_indicator: ^4.2.3
  google_fonts: ^6.1.0
  # Data
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  # Charts
  fl_chart: ^0.63.0
  # Helper
  connectivity_plus: ^5.0.2
  http: ^1.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/models/
    - assets/images/
